//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGAsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRiderEntry
    {
        public int Id { get; set; }
        public int EventTeamEntryId { get; set; }
        public int RiderId { get; set; }
        public int PonyId { get; set; }
        public Nullable<bool> Paticipated { get; set; }
    
        public virtual Pony Pony { get; set; }
        public virtual Rider Rider { get; set; }
        public virtual EventTeamEntry EventTeamEntry { get; set; }
    }
}
