//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGAsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MgaEntities : DbContext
    {
        public MgaEntities()
            : base("name=MgaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pony> Ponies { get; set; }
        public virtual DbSet<Rider> Riders { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<TeamEvent> TeamEvents { get; set; }
        public virtual DbSet<TeamRoster> TeamRosters { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
