//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGAsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rider
    {
        public Rider()
        {
            this.EventRiderEntries = new HashSet<EventRiderEntry>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public System.DateTime DOB { get; set; }
    
        public virtual ICollection<EventRiderEntry> EventRiderEntries { get; set; }
    }
}
