//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGAsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamRoster
    {
        public System.Guid TeamRosterID { get; set; }
        public string TeamName { get; set; }
        public string Season { get; set; }
        public string Rider1 { get; set; }
        public string Pony1 { get; set; }
        public string Rider2 { get; set; }
        public string Pony2 { get; set; }
        public string Rider3 { get; set; }
        public string Pony3 { get; set; }
        public string Rider4 { get; set; }
        public string Pony4 { get; set; }
        public string Rider5 { get; set; }
        public string Pony5 { get; set; }
    }
}
