//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGAsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamEvent
    {
        public System.Guid TeamEventsID { get; set; }
        public string EventName { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventType { get; set; }
        public string EventPriority { get; set; }
        public int SeasonID { get; set; }
    
        public virtual Season Season { get; set; }
    }
}
